#!/bin/sh
#
bldone () {
  t=$1 
  cd $t
  # The following distclean will fail on a clean directory
  # Ignore the failure
  make distclean
  ./configure
  if [ $? != 0 ]
  then
	echo build failed
	exit
  fi
  make
  if [ $? != 0 ]
  then
	  echo build failed
	  exit
  fi
  cd ..
}

bldone libdwarf 
bldone dwarfdump




