#!/bin/sh
# CPTOPUBLIC [uv] [nouv]

usemsg()
{
  echo "CPTOPUBLIC [uv] [nouv]"
  echo "where uv means update version strings "
  echo "where nouv means do not update version strings "
  echo "One of uv or nouv is required..."
}

if [ $# -ne 1 ]
then
  usemsg
  exit 1
fi
uver="n"
case $1 in 
  uv) uver="y" ;;
  nouv) uver="n" ;;
  *) usemsg  ; exit 1 ;;
esac

s=/home/davea/dwarf/code
cd $s
pwd
t=/var/tmp/dwarf
echo target is $t
if [ $uver = "y" ]
then
  sh UPDATEDWARFDUMPVERSION.sh
fi
rm -rf $t
mkdir $t
cp -rp * $t
